---
- hosts: localhost
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
    - include: tasks/droplet.yml



- hosts: newdroplets
  user: root      
  vars_files:
    - vars.yml
  become: yes
  tasks:
    - include: tasks/provisionJenkins.yml
               

